#!/bin/bash

### BEGIN INIT INFO
# Provides: watchdog
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start a watchdog at boot to monitorize files created on /home
# Description: Start a watchdog at boot to monitorize files created on /home
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/home/test/watchdog-service
DAEMON=$DIR/watchdog.py
DAEMON_NAME=watchdog
BIN=/usr/bin/python
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
log_daemon_msg "Starting system $DAEMON_NAME daemon"
$BIN $DAEMON
log_end_msg $?
}
do_stop () {
log_daemon_msg "Stopping system $DAEMON_NAME daemon"
kill `cat $PIDFILE` && rm $PIDFILE
log_end_msg $?
}

case "$1" in

start|stop)
do_${1}
;;

restart|reload|force-reload)
do_stop
do_start
;;

restart|reload|force-reload)
do_stop
do_start
;;

status)
status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
;;
*)
echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
exit 1
;;

esac
exit 0
